[package]
name = "oof"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
chrono = "0.4"
chrono-english = "0.1"
dotenv = "0.13"
regex = "1.0"
reqwest = "0.9"
scraper = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tera = "0.11"
